apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system #need to create a GitRepository resource named flux-system
  path: "./infrastructure"
  prune: true
  wait: true
  healthChecks:
    # Add health checks for other critical infrastructure components if desired
    # - apiVersion: ...
  dependsOn: # <<<<<<<<<<<<<<<<<<<<< THE KEY ADDITION
    - name: infrastructure-crd
      namespace: flux-system # Ensure this namespace matches your infrastructure-crd Kustomization