apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 30m
  chart:
    spec:
      chart: jenkins
      version: ">=5.8.68 <6.0.0"
      sourceRef:
        kind: HelmRepository
        name: jenkins # the Chart is jameswynn/homepage
        namespace: flux-system
