# Wallabag Service
apiVersion: v1
kind: Service
metadata:
  name: wallabag-service
  namespace: wallabag
spec:
  selector:
    app: wallabag
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
# Clean Wallabag Deployment - Init Container + App Container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      initContainers:
      - name: init-wallabag
        image: wallabag/wallabag:latest
        command: ['sh', '-c']
        args:
        - |
          echo "=== Wallabag Initialization ==="
          
          # 1. Wait for PostgreSQL
          echo "1. Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres-cluster-rw -p 5432 -U wallabag; do
            echo "PostgreSQL not ready, waiting..."
            sleep 2
          done
          echo "✅ PostgreSQL is ready!"
        env:
        - name: SYMFONY__ENV__DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DOMAIN_NAME
        - name: SYMFONY__ENV__DATABASE_DRIVER
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_DRIVER
        - name: SYMFONY__ENV__DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_HOST
        - name: SYMFONY__ENV__DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_PORT
        - name: SYMFONY__ENV__DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_NAME
        - name: SYMFONY__ENV__DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_USER
        - name: SYMFONY__ENV__DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_PASSWORD
        - name: SYMFONY__ENV__REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__REDIS_HOST
        volumeMounts:
        - name: wallabag-data
          mountPath: /var/www/wallabag/data
        - name: wallabag-data
          mountPath: /var/www/wallabag/web/assets/images
        - name: wallabag-data
          mountPath: /var/www/wallabag/var
          subPath: var
      containers:
      - name: wallabag
        image: wallabag/wallabag:latest
        command: ['sh', '-c']
        args:
        - |
          echo "=== Starting Wallabag ==="
          # Start the Wallabag application - create db schema if not exists
          php /var/www/wallabag/bin/console wallabag:install || exit 1
        ports:
        - containerPort: 80
        env:
        - name: SYMFONY__ENV__DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DOMAIN_NAME
        - name: SYMFONY__ENV__DATABASE_DRIVER
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_DRIVER
        - name: SYMFONY__ENV__DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_HOST
        - name: SYMFONY__ENV__DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_PORT
        - name: SYMFONY__ENV__DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_NAME
        - name: SYMFONY__ENV__DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_USER
        - name: SYMFONY__ENV__DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__DATABASE_PASSWORD
        - name: SYMFONY__ENV__REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: wallabag-secret
              key: SYMFONY__ENV__REDIS_HOST
        volumeMounts:
        - name: wallabag-data
          mountPath: /var/www/wallabag/web/assets/images
        - name: wallabag-data
          mountPath: /var/www/wallabag/data
        - name: wallabag-data
          mountPath: /var/www/wallabag/var
          subPath: var

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: wallabag-data
        persistentVolumeClaim:
          claimName: wallabag-data-pvc
---
# Wallabag persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-data-pvc
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi