apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  values:
    adminPassword: "secure-pihole-admin-password"
    
    serviceDns:
      loadBalancerIP: "192.168.100.53"
      
    persistentVolumeClaim:
      size: "5Gi"
    
    extraEnvVars:
      TZ: "Asia/Jerusalem"