apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: worker-node
    tolerations:
      - key: "node"
        operator: "Equal"
        value: "worker-node"
        effect: "NoSchedule"
    
    # Disable built-in PostgreSQL HA subchart - using CNPG instead
    postgresql-ha:
      enabled: false
    postgresql:
    enabled: false
    # Configure Gitea to use external CNPG database
    gitea:
      config:
        database:
          DB_TYPE: postgres
          HOST: gitea-postgres-rw.gitea.svc.cluster.local:5432
          NAME: gitea
          USER: gitea
          PASSWD: Asd424941_a
          SCHEMA: public
    persistence:
      enabled: true
      create: true
      mount: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce
      storageClass: "gcs-storage"
