apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: worker-node
    tolerations:
      - key: "node"
        operator: "Equal"
        value: "worker-node"
        effect: "NoSchedule"
    
    # Disable built-in PostgreSQL HA subchart - using CNPG instead
    postgresql-ha:
      enabled: false

    # Configure Gitea to use external CNPG database
    gitea:
      config:
        database:
          DB_TYPE: postgres
          HOST: gitea-postgres-rw.gitea.svc.cluster.local:5432
          NAME:
            valueFrom:
              secretKeyRef:
                name: gitea-postgres-credentials
                key: database
          USER:
            valueFrom:
              secretKeyRef:
                name: gitea-postgres-credentials
                key: username
          PASSWD:
            valueFrom:
              secretKeyRef:
                name: gitea-postgres-credentials
                key: password
          SCHEMA:
            valueFrom:
              secretKeyRef:
                name: gitea-postgres-credentials
                key: schema
    persistence:
      enabled: true
      create: true
      mount: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce
      storageClass: "gcs-storage"
