# Default values override for Netmaker non-HA setup
baseDomain: "netmaker.gwynbliedd.com"

server:
  replicas: 1
  storageSize: 256Mi
  
ui:
  replicas: 1
  
mq:
  replicas: 1
  username: netmaker

dns:
  enabled: false
  
service:
  type: ClusterIP
  
ingress:
  enabled: false
  
db:
  type: "postgres"
  
postgresql-ha:
  enabled: false