apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netmaker
  namespace: netmaker
spec:
  interval: 15m
  chart:
    spec:
      chart: netmaker
      version: "0.3.5"
      sourceRef:
        kind: HelmRepository
        name: netmaker
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    baseDomain: "netmaker.gwynbliedd.com"
    
    server:
      replicas: 1
      jwtDuration: 43200
      racAutoDisable: "true"
      storageSize: 256Mi
      
    ui:
      replicas: 1
      
    mq:
      replicas: 1
      username: netmaker
    
    dns:
      enabled: false
      
    service:
      type: ClusterIP
      restPort: 8081
      mqPort: 1883
      uiPort: 80
      
    ingress:
      enabled: false
      
    db:
      type: "postgres"
      host: "netmaker-postgres-rw"
      port: 5432
      username: netmaker
      database: netmaker
      
    postgresql-ha:
      enabled: false