apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netmaker
resources:
  - cnpg.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: netmaker-values
    files:
      - values.yaml=default_values.yaml
configurations:
  - kustomizeconfig.yaml