apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository # resource that defines a Helm repository source
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 24h
  url: https://dl.gitea.com/charts # URL of the Helm repository source