apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository # resource that defines a Helm repository source
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 24h
  url:  https://helm.runix.net