apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository # resource that defines a Helm repository source
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts # URL of the Helm repository source
