apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository # resource that defines a Helm repository source
metadata:
  name: vscode
  namespace: flux-system
spec:
  interval: 24h
  url:  https://nicholaswilde.github.io/helm-charts/