apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: wallabag
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main  
  url: https://github.com/GutsButcher/wallabag