apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gwent.gwynbliedd.com`)
      kind: Rule
      services:
        - name: homepage
          port: 80