apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gwent-game
  namespace: games
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gwent.gwynbliedd.com`)
      kind: Rule
      services:
        - name: gwent-game-service
          port: 80