apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  values:
    nextcloud:
      host: cloud.gwynbliedd.com
      extraEnv:
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "cloud.gwynbliedd.com,nextcloud.gwynbliedd.com,storage.gwynbliedd.com"
      existingSecret:
        enabled: true
        secretName: nextcloud-credentials
        usernameKey: username
        passwordKey: password
        tokenKey: token
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql 
      host: nextcloud-postgres-rw.nextcloud.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-credentials
        usernameKey: username
        passwordKey: password
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false

    