apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wallabag 
  namespace: wallabag
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`wallabag.gwynbliedd.com`)
      kind: Rule
      services:
        - name: wallabag-service 
          port: 80