# CloudNativePG Cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-postgres
  namespace: gitea
spec:
  instances: 1
  
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      secret:
        name: gitea-postgres-credentials
        
  storage:
    size: 2Gi
    storageClass: local-path  # default k3s storage class, adjust as needed
---