apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: ">=12.4.0 <13.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitea # in jameswynn/homepage => use jameswynn
        namespace: flux-system
