# CloudNativePG Cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-postgres
  namespace: vaultwarden
spec:
  instances: 1
  
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-postgres-credentials
        
  storage:
    size: 2Gi
    storageClass: local-path  # default k3s storage class, adjust as needed
---