---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: vaultwarden
spec:
  encryptedData:
    uri: AgB0BhBhr1mozo9HWyinQmOlyFmb+cnHvmMxP1hVWNUD1XUKeNb2JV5cDPTBxJSWFlYsfwy2o/xBWE+mfwC7+ZMziOpy8wvzJwRcCZCs2VyKUF/YzqqCdiO1yQ8u0o9K5VSiGbd13lhAyRxc+6LwsEKfOS/uS2P/5CFyr+TqMO5pF78O9td0j1OZPHPSobVnMAP6dcTBsWbmR4Q1RSWySXtrtFrir4KV/9XHovm4HNkttlbIw/2HjEA7+7S90DCO7KnOFGembggiLiUnx58fpYtHBQK+WnrAxhsLs3KK/qgdiQRCpeE3bc5EyafK51pVRjo1RFueeCRo2xkYUhTi9HNyJhpWo49ChDHUDLAM3axPmmS4mYZ3Ohs9mxFgV+XMrobpX4SERXMndpp2VWS1FwClQBIPvTt/65cAfEOTgYOfEL/e/FQ1efsqyLIFzgwZFap50IxX6rqXkye6bDNeUpJO5dFJUN2PJbu5MkYjUIbmtpmzyCjvYH+J1dGrhr/WQWFmpYxZTiwfehCOfDw9yMpoazypjx8TK/WND7xR2KgMI1iHRo6kzDfTX2vrMOk6BN1L8IZT2Wz3YmOUoGcUIYXSuVycVFmjC95pO58DjSMXWMw1brwLJhEGUhDD6O+rTVD0fFnQtnweLhMNUzGIMVL8Yt8XC/XSLyTjW4r/Rc1zG3uEMDMJJs6RK4FJPrfqfiMPvaqb14k3+B4sLDHseST+78Sd7QFcH+0uPTLbJEe+KHZR/24slZU8Ym5q1jskZ8ZlNObTGRdBly73OeyBLbrwYaPhWdGtrFFZp3oZiim1GK/Go0KPCoDrIY1xJM/ZFsl3Wvs5jvcUuKg=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: vaultwarden
