apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-secret.yaml
  - cnpg.yaml
  - db-connection-secret.yaml
  - smtp-secret.yaml
  - admin-secret.yaml
  - helmrelease.yaml
