apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 12h
  crds: CreateReplace #add this line for avoinding pool CRs waiting for CRDs issue
  install:
    remediation:
      retries: -1 #keep retrying indefinitely on install failures
  upgrade:
    remediation:
      retries: -1 #keep retrying indefinitely on install failures
  values:
    controller:
      nodeSelector:
        kubernetes.io/os: linux
    speaker:
      nodeSelector:
        kubernetes.io/os: linux
