apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: ">=2.1.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: jameswynn # the Chart is jameswynn/homepage
        namespace: flux-system
