apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gwent-game
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./kubernetes"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gwent-game
  targetNamespace: games