apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-values
  namespace: authelia
data:
  values.yaml: |
    domain: gwynbliedd.com
    
    pod:
      replicas: 1
      env:
        - name: TZ
          value: America/New_York
    
    configMap:
      existingConfigMap: authelia-config
    
    secret:
      jwt:
        key: JWT_TOKEN
      ldap:
        key: LDAP_PASSWORD
      storage:
        key: STORAGE_PASSWORD
      storageEncryption:
        key: STORAGE_ENCRYPTION_KEY
      session:
        key: SESSION_SECRET
      duo:
        key: DUO_SECRET_KEY
      redis:
        key: REDIS_PASSWORD
      redisSentinel:
        key: REDIS_SENTINEL_PASSWORD
      smtp:
        key: SMTP_PASSWORD
      oidc:
        hmacSecret:
          key: OIDC_HMAC_SECRET
        privateKey:
          key: OIDC_PRIVATE_KEY
    
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 1Gi