apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/authelia
  - ingressroute.yaml
  - forwardauth-middleware.yaml
  - users-configmap.yaml
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: authelia