apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: authelia
data:
  users_database.yml: |
    users:
      gwynbliedd:
        disabled: false
        displayname: "Gwynbliedd"
        # Password will be set via script - placeholder for now
        password: "$argon2id$v=19$m=65536,t=3,p=4$pZht+ZdSI1DFhOpxObWBcg$s3GkFmEto3H5LC4t0WB3SeJ52+59ffvlWckFGMeOdIE"
        email: gwynbliedd@gwynbliedd.com
        groups:
          - admins
          - users