apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: ">=8.0.2 <9.0.0"
      sourceRef:
        kind: HelmRepository
        name: nextcloud # the Chart is nextcloud/nextcloud
        namespace: flux-system
