---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-auth
  namespace: homepage
spec:
  encryptedData:
    users: AgAQ0UaMTeMZcpvoL2ayvvZlcN8DVxXuWbojKY7iKZFZVz/4S1tMBLfCeXuFUkooqqppvy3hzscQfttuRC1eatA2qn5eGrX6iGz+oDLGPi2PfnomzXPgPXgZyMH9v3N0DxIKyPCSp251O1Y35SFyWTzAdAPD7NH2U3jIS4dzxTwTggshcjkumQh+Rwn5HJ2X5WivXfguU7PK+gyCmTomLrmbB3cURBo0El7mV+1vXNk1utMtG6o0IJsqFN9MZtC8ZByC6lbarpc8ob0gHywcS+916f6Ne5mN0ApQwEWSxtASru/Qer1juAB7xQAjFc3qE8t6fnDGIfZiaTfwudk4ZguQU+byZ/wiy40mZ1oR9+4hJ6mAORoDEq0Fw/JJr4KhMe+QZpFhh+J/MQpo9Z8m3qxY18m5fCMJPFnCPSmY04/i5zTA0M7ifsQyyOcMVVDqM51wGp1PH6Z4vGS/9BUE7z19qUGcoSl/ZLWogPfb/zlfOu3xhnJJefVwsnnb3lGM/hPR0gwQMmA+EaR71CvSlzKM8zjIANb69v66KyuZKgcwtDohhvWAfSAiOMj5urxrGxkREZsXHHVvDGPp0LZ2DIugKLWXN4IIfFoPqbeADce8M2pehVu1jqJboqDC9x5cvj1YRpcxW1VHIWP5rVPoUjwS9OntZfncxmvw+Zd9WkHEwCFSbBdiKWDXuQ80mdc1E434naZPGXJwZVFQ9pH9F8qYRfEaWc7FAnKwgFCwAanPjKQNVF/puMUbQPYU08o=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-auth
      namespace: homepage
