apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  interval: 30m
  chart:
    spec:
      chart: linkding
      version: "1.1.20"
      sourceRef:
        kind: HelmRepository
        name: linkding
        namespace: flux-system