---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCbjiByi1S1FXwCQCXWU3VB9R8HZF4XsifJaKwN97RalnSucDp83c8wgwdBh5c84ILonFMLkm42ZkXeqtP1jg3HkgdBZlQIk2JeQhUL9EjPnIpVF8iygUMXnt+92nUPR2JTqHRynW5t8aqPWEHGymasDiRgvA3jsgIBcpsMucSIhTq47VIQEb0JaqYamvQRHNGdI8PTvLJDMNE7oJcp7h3QjtFebLHUZ2q19YBSVR3f9VQGRvKPRSUj+VTKd7YXdt4EVbUe3Wll8aEWbNIvtEUG0rtRXWouOwelrbCuuzzdOn8NT4eXN8r1OLggqOlyIvJ94TKtimCpgnjKqAulwOimJhS/22ZpffUT9/1mYVT+KKK1T98oldIDUMRMTjMWz9IrDVpHie5XF4ocdaZhakJ/+GSprIjAzcy0oX9lrcGteadY1NIxlvDiBwsQqMw9i6VrfyFxQORHZ1dYmMPd0dNx0qSWcNhuEBP3B1kTXbK/RlHsZJtu5/ZOU/hlmm0SSOLqFrlx+Yjlq7/sAjBptfxHIofysKQyNM7CArlvjq9zP56ha171mKHYREjPM6NzAxKkqGFmSybw7Bes6HOVGRRbTHe7NLO7E3DigtYYm6mvzaCWueWCm/WmW6WdlGawMmEHLu8Gz5eKAwdtafLAcj0rrRt/EYs/Qg5KA506jUhxafS7TAFpulH3d75rI6cgpjr90Xz4uZiXugKyRwOAVBF4wmEMEg==
    RUSTFS_SECRET_KEY: AgA8OUkmhlZlAmeE1fK5JccekrYZTFMSwNHpwkzyGMMUa/r/Z+Sf+2llKbr6E322mPkoSGu0H8IkNl9gwyS0b+7Z6oHJvp/pxOsoCrHgqAoE6cLrEhflIezFBBRbNOSnxVA2/x+6tKIOiy6Cc/pQv97j98msSmcUU02EIFpMzNXy/sTxIATcPHDpD9SmHInLnNIiD3OxA5PriYRBTVZrifnPTQKHcc6Swg6AbSOphiMvghoXio1bliVzfTvrbUfxcQBplLNV/fFv8ibTeBZXCpQy1UDd8iZDR4R4q/5bTWT0shuHTC23kFewy4KDHhk+2oIa9IIWMP+gFpCSacm4S8rQcR8MUiUFIGK0fN9kpOpntVyBXzN8PaONS8wniemfPY0x32WSYZMtQz3mCPVpRMuQdzLLuUtxUDYyowewxRd3ay/A7D1ZdDs9fOFkUStFybLU+CeVvdWOvuuEyQTNa1HFqjUuY03gQUg58/QwRUXoHgkKLuwKIH6ERvCag0nelCzXYmLt7TkA2izbkM/zaN+ex0G56erE8bevR4of2LJhIRA4rYNLMZFME7qVuomuvRvoL2hIOI5vvt5OaG7PTme2FNGiQAAtp5OvJ503QldxQ3WSn2cbdlG7qqBUavecW0/S4kxZr3usepyuZa0HKGQEn+CYCiu79M+1JYFBvcK6qhpzpGQiGtiLwsjPwlBFJORZ59VDTIe0uATXfMBORdhGqbMuE1l0zTtLm7SRfK0biwc9QjJPpwTb
  template:
    metadata:
      name: credentials
      namespace: rustfs
