apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  values:
    service:
        extraPorts:
          - name: websocket
            port: 3012
            targetPort: 3012
    vaultwarden:
      domain: "vaultwarden.gwynbliedd.com"
      adminToken:
        existingSecret:
          name: admin-token
          key: token
      data:
        pvc:
          storageClass: local-path
      

      passwords:
        iterations: 350000  # KDF iterations - required for mobile app
        hintsAllowed: true
        showHint: true
      database:
        type: postgresql
        existingSecret:
          name: db-secret
          key: uri
      # Restrict signups - only admin can invite
      signup:
        allowed: false      # Disable public registration
        verify: true        # Email verification for invites
      invitations:
        allowed: true       # Admin can invite users
        orgName: "Gwynbliedd Vault"
        expirationHours: 48
      # Gmail SMTP Configuration
      email:
        smtp:
          host: "smtp.gmail.com"
          from: "abdulla.amash@gmail.com"
          fromName: "Gwynbliedd Vault"
          security: "force_tls"
          port: 465
          username: "abdulla.amash@gmail.com"
          auth: "Login"
          existingSecret:
            name: "vaultwarden-smtp"
          requireDeviceEmail: true  # Email on new device login 