apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  values:
    vaultwarden:
      domain: "vaultwarden.gwynbliedd.com"
      adminToken:
        existingSecret:
          name: admin-token
          key: token
      data:
        pvc:
          storageClass: local-path
      passwords:
        hintsAllowed: true
        showHint: true
      database:
        type: postgresql
        existingSecret:
          name: db-secret
          key: uri 