apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  values:
    vaultwarden:
      domain: "vaultwarden.gwynbliedd.com"
      data:
        pvc:
          storageClass: local-path
