apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vaultwarden.gwynbliedd.com`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 80