apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - web
  routes:
    # Websocket route - must be first (more specific)
    - match: Host(`vaultwarden.gwynbliedd.com`) && PathPrefix(`/notifications/hub`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 3012
    # Main application route - catches everything else
    - match: Host(`vaultwarden.gwynbliedd.com`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 80