apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netmaker
resources:
  - ../../base/netmaker
  - ingressroute.yaml
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: netmaker