apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vscode
  namespace: vscode
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "1.1.1"
      sourceRef:
        kind: HelmRepository
        name: vscode
        namespace: flux-system