# CloudNativePG Cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: docmost-postgres
  namespace: docmost
spec:
  instances: 1

  bootstrap:
    initdb:
      database: docmost
      owner: docmost
      secret:
        name: docmost-postgres-credentials

  storage:
    size: 2Gi
    storageClass: local-path # default k3s storage class, adjust as needed
