apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins
  namespace: devops
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jenkins.gwynbliedd.com`)
      kind: Rule
      services:
        - name: jenkins-jenkins
          port: 8080
