apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: obsidian
  name: obsidian-deployment
  namespace: obsidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian
  template:
    metadata:
      labels:
        app: obsidian
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        image: lscr.io/linuxserver/obsidian:latest
        imagePullPolicy: Always
        name: obsidian
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 3001
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /dev/dri
          name: dri-device
        - mountPath: /dev/shm
          name: shm-volume
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: obsidian-config-pvc
      - hostPath:
          path: /dev/dri
          type: Directory
        name: dri-device
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: shm-volume
