apiVersion: v1
kind: Service
metadata:
  labels:
    app: obsidian
  name: obsidian-service
  namespace: obsidian
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: obsidian
  type: ClusterIP
