apiVersion: v1
kind: Service
metadata:
  name: traefik-metallb
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: traefik-pool
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.100.210"
  selector:
    app.kubernetes.io/name: traefik
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
