apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian
  namespace: obsidian
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`notes.gwynbliedd.com`)
      kind: Rule
      services:
        - name: obsidian-service
          port: 3000
      middlewares:
        - name: basic-auth
          namespace: homepage