apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  values:
    existingSecret: "pgadmin-credentials"
    secretKeys:
      pgadminPasswordKey: password
    
    persistentVolume:
      ## If true, pgAdmin4 will create/use a Persistent Volume Claim
      ## If false, use emptyDir
      ##
      enabled: true

      ## pgAdmin4 Persistent Volume Claim annotations
      ##
      annotations: {}

      ## pgAdmin4 Persistent Volume access modes
      ## Must match those of existing PV or dynamic provisioner
      ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
      accessModes:
        - ReadWriteOnce

      ## pgAdmin4 Persistent Volume Size
      ##
      size: 5Gi
