apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pgadmin.gwynbliedd.com`) 
      kind: Rule
      services:
        - name: pgadmin-pgadmin4
          port: 80
