apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  values:
    controller:
      jenkinsAdminEmail: "abdulla.amash@gmail.com"
      admin:
        existingSecret: jenkins-admin-secret