---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCXKLEjXcnph6wf1p1zYVW9Qo5YuFlbhPKdYj06daDxVlySGUUh1qMteFKOTaHGbR0UZ2t1L8ZXmMpB02gJY9YyGoyi187UPvsnjS0kiILdtDWlUHTumhoWj5SjPN/Nx2gcELPJ9K4VoXK72kXj431+xoSZK1KHhVymVKm3ZuaYUbEogPmoeY7SocfF2Ph9+xtJ7i3O58A9VUOmJbDPLo4kegZMP2Nms5bS0yzjUYcpAC8/LQUu3mc+YUoWfJ3iC9/KldSL4hBOUViCoIEQGqTwEalfkjstMUm5dzlppS8tH6IC/7b+V+f7aFJev7nwh1qEydwdaXgGofh2qKzISekS67ExALW+yo8U244GhSXR3mqUBUIslFHzaaCEiTv5bCXoxUccFdfV3t0bSx8iAQ4j7tu03e7yIJfvg4+XEbtj+UFRDtUpb4yAIRMa5oFebMz4OBgPhrWZTMYFDH54CP3imhmKMO+PBYmOgjS7OUUop8YSu2piGyp07mx2KGfRXgNwcCbx5UwbxhvuSqOW0mKRdRAJxX39xYV8UEQ43xtI7SWiew3XJpKlTKKREium2hUlPtIH3Oe3+TJB9x7eWQFwlVGDydQbco+Pnw91uieLgreOYesYFEd4gW+++0FmMqkkS79OQonTywoO/eTdOLH8d3Woq4EZG3AymkbWHSlVM7ggJa34L6qRM+al5eNCdIpJr7k1e5sH9KaiO17s
    admin-user: AgCFp+maTUf2y53ctvG66hZ8zxb/PICMHvXi8/IMJ86iZKrQjQmBquizTQax6274EfLn0qzDq3+4BBscwyvTMzZigbqQnlTH9GbF4z/ywyzWnAbHfx+jJojUoAwwUDbMt6iJJwgfoRbFTgGaUcFxCtoS/sXtHZ8LoFmnpeRrctnYLrdQ4F21/sDr9WmsgHTyD/ggWL3L+9ckKQBQawPGIqsb2dRVfMB0tB5D9W6jLHVDC6V7nTYxS3AcTKLYjxJn0TVBbGP4/4LrCQ7cGoIDcqcOudxeiQSPDoyp4w/qHIMBo0xYeUNq5Ci3TNzPzOV7B7KGFkTW+TKRdw5cpYHT8C9DqtBwU78dMsactkt9Zz/jX0EOCvzHis512XO4hc4Mq2qTp4iFC93iT7vDyswzD2zVVvzGBcQlVGgKyr6m3LDBiD7jBTFb/PtRFN33AT5TVNpW3AC8zTj54SPn7l9abFHE3QTJ85qsWmoAKAfZRyx+92aWDEI5sOL0veKXTJ99vaf6VegXaiVEIF31iq8XLCzmPYx9Mc/yWfFAHZjsbMmVoq0i/b02v0tdNIeVUqEYBKv+XbcT/F1edlqtheiGJmUrNRzkH2288W1gZ/wXHgf5Et8kuUQT31RJr9HSL/Ww0fAKF8M8TL1Hn5tqSHZzrA4leYqDz06lS+uaGLd3c8I5zHh69DThFJ5Ti6t+LUBtEeotsUa52A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
