apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring 
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.gwynbliedd.com`) || Host(`monitor.gwynbliedd.com`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80