apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/instance: syncthing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syncthing
        app.kubernetes.io/instance: syncthing
    spec:
      hostname: syncthing-homelab
      containers:
      - name: syncthing
        image: syncthing/syncthing:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: STGUIADDRESS
          value: "0.0.0.0:8384"
        ports:
        - name: web-ui
          containerPort: 8384
          protocol: TCP
        - name: tcp-transfer
          containerPort: 22000
          protocol: TCP
        - name: quic-transfer
          containerPort: 22000
          protocol: UDP
        - name: discovery
          containerPort: 21027
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /var/syncthing
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /rest/noauth/health
            port: web-ui
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /rest/noauth/health
            port: web-ui
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: syncthing-config
      - name: data
        persistentVolumeClaim:
          claimName: syncthing-data
      securityContext:
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: node01