apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
spec:
  type: ClusterIP
  ports:
  - name: web-ui
    port: 8384
    targetPort: web-ui
    protocol: TCP
  - name: tcp-transfer
    port: 22000
    targetPort: tcp-transfer
    protocol: TCP
  - name: quic-transfer
    port: 22000
    targetPort: quic-transfer
    protocol: UDP
  - name: discovery
    port: 21027
    targetPort: discovery
    protocol: UDP
  selector:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing