apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  values:
    common:
      # env variables
      variables:
        secret: {}
        nonSecret:
          USER_UID: '1000'
          USER_GID: '1000'
          TZ: Asia/Bahrain
          LD_ALLOWED_HOSTS: "linkding.gwynbliedd.com,localhost,127.0.0.1"
          LD_CSRF_TRUSTED_ORIGINS: "https://linkding.gwynbliedd.com"
          LD_REQUEST_TIMEOUT: "60"
          LD_TESTO: "TEST"
      persistence:
        enabled: true
        volumes:
          - name: "data"
            size: "5Gi"
            containerMount: "/etc/linkding/data"