apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vscode
  namespace: vscode
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`code.gwynbliedd.com`) 
      kind: Rule
      services:
        - name: vscode
          port: 8443
      middlewares:
        - name: basic-auth
          namespace: homepage