apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: ">=1.47.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: pgadmin
        namespace: flux-system