---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-db-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgASnY63FoSej9oMIuIVyAs1YWvjREvnreVSwEnUVVjIWj3SjMuoezqPywh2vZ4AMLNMH9+RNCwk80WpANb6jkvFjWRk+5pRJiDXjW49j6KbxMgWXM2draD57MSzUQMqk60jNDq68i8+onj6mCrv5i/I15cs/XIa3GKLSLWoxxkpWtRgocKgF1l4lTPO3ttykQCnDp/h56wsDBzuyrLmGBh/ULtgKJvbwO9jXRiU2VDofPZHQcPEZnKc4BFfhEa1Iexwx+rYFpPKmnI4m0ofdsWCl4hiiOM2OFo+vlneW6CVXx2VcFNOTpEWPIuaPmNNA7X3gj6GFIjWFNJwav+twGWAXoSqwTTVArrLdIWoTOTWkMV9qMGkEAwxCav1Qh1aGH01GYF06iws6fcKMzZuWuxAECzJ4SBCdQPJoJLxa/twtjq6h/hDDKOb5x0FC00xVVbiF/YTdBGuD0etLTIXgqrCtMU47BhtD68HAxT3i2QdT9smq+XJpEnEp+emJOseAdRVnmLwpRNooJScf65NtbqhQAM+aSyhAIJaQKkV94ayi0oZw2LxDcGJKqOE1JnCd5x/FZuztGGqBEUSA4mDPAO6So6QrfvJXtovv09+G44j8qIHxe7srrrzIek7nHXchC4AfoCsd0NwUJOEHtIUlvUEccZk+X8ElfWIdspEbwRzuTnq3C+ZTRAQ0OWxxwmpWizjHtJWmsc5oqCNAw==
    username: AgBbRDyTZowHmnlWjflJ2dL3AfEAO5312jHu3U8Cdw2AaX8UH34KVjVoDDkd1CdYrE47m7rulRNy4TkxRAWst0n0jfAw2aAEFPVDCWmLYoPKHVdz/ewN46fNFcII5ALP4lzjE18C19ZXfB2W/mUWpYYsG9e6AMgSHxbiYTOyMIZHjUMPdVqoxy24qy1dpmku3/FfeC2T1y9uR7Ovy252V60eB6AObeHEeeyzzmZU4+/9m7m/d8CpalVysP3mex6zrxPodzs818Z59xZ1Wf/jLmgZW5N/Z0cECedLhny/NC6jJr9ddWU9yQ2xRT5GJTQhVOvzbRVEyf2Op2J6iNy3/wHusAwJUJazqVE6I5YXeLhfpk+aLEyF7kiMBdoeg3u41Ftwh4HA0mZrsYuue3ozlzxH7MRse6VmV6DulM0289ZtTrAuXcigcvZAfh+RxMDdG2TF1ufmM+yPgmhfFy6cyFHLSkLOTmCfiVxj1GLvHBKBnYo0IbxvQOISVLgCCQD34tvcqZOfINfzSOdoqBge+TLKoqkL9oV1LtXk+odgof6uDaI3rWJB+fh+3x/clWrk9FtRsR3P61t6Q5XQwrGPIfH9C/mYec/8fKEqxQg+uwdKHzab5mGymIifFIBePk02V0QWKSZBh/+St8rs6D/h85HmQPJtDoN1vWIZv5vlqnlqRu0bvpGdBEZ65XQrlwZZvla0krSZl91oelE=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-db-credentials
      namespace: nextcloud
