---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: treelink-backup-s3
  namespace: treelink
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBOaDDBuPMw5PEOJuAxpNo+GumCY42E2NEcOJCxBKH9XTxEUuevJNlPFwMFcxb0WlMQKPjJohg+Eut/kq2OsKZooeBpM4BRZMkdlt19b/YCcKzwK9CkcnBbkM6GT/XEKjj+sS6yclXAPGHcaUc46jttTLKLL24Xp3uGNzOhpMMVnVNO4k0Au0uuvGmbRolkN9/wMURlLjV5NORtpx9MZ18WBqoKYsn/5SbmTjLVEqbAQWryXyEnV4wGid0Bt9WGxZki6KoBRql0CRjUfNVs+R3jCgXRQ8CtJ119SqP9aFpkBspAthInvcOYQvmTVRVGiijRYzhsX8G+pN2lfwU2+oxD28luYrwmBKkGa9AvMZoffsptJ42XBhAzrY7GTY1yXVDAZ2+t3QTdHs/LDFWjoBTp7y/9wzKhRgOctpZ+UU9MxtwbhZuWeK6n6Q/p8mBK0vJZYmyJbbUakUQttD5w5udgawTARjza8TtAJOtjou0R2i6cCTIlWAg9E15zoaSzGoY+hD2djz0yiS0Rk454JR2ntaCFVQ0uWlkvRmOxqDmY6kFs4PRTkUc5d7nDxbkUgXndqTRl3LWNgLBievahVujer8C5KkNGR8ivmfEhHR6jyLqZpqSpW019Rj0QntCVyq4lCehg6M+9mPKhc6uc4LR277kG7nhdUaZIhOBhd5qw6DvRKD8JBgVuG57vM18LabsKA+s2LNZWuMbfB+iQ11MV4RgAmA==
    ACCESS_SECRET_KEY: AgBEmSXhO9p2CYsZk3dcveFuHQzdZld+e3VJ1bw/tC8Nyif13f7HbuXjr43M8GN1k6UhnP+YzcRabIBfV1J10gxdEn05KekK/uBp1euLnPTba1+XM/K0RieNv5QO+jfaQ5H/ju/AGFdTsHa+hWJTXu9IuI3DTeNlX26Kud6cx6qOY9yHRuOf07TbEs8vI6hjX+CMjDoWHHRkqaE0vbOTbQuS5NqAYufzEOlrPYT1PW5lNeevN8vLkXhZa79TOorVrlZT/dhitCbfG1861ncnOZjieUlLNNHRVjYVz2tKJnAvWE4+LKHQY4KdGPnm/MAUIvMrSRGYsrwwRLyeFsby5YYcBCdy8yY6WO37EBDbG4ZQYvn9M+ypgEJpg9VL9AVQ1DZrWkRVZXajUXA/73IW4XXnFUZNqsSidohjfjPR1ZWMEeFHOfcDESyAQv3a+DVv4TldJbR/5twwhtNvGerY8W90hqHsAjRLjCiX8toCwwf5CjINDmPfTG564Ns2/CXM+fZh1mmyXSQ9+6vfzH2p2YX9GddJvV2vULwSd8P7yjyqhlp3J5VM0OYu10Q5l4JDUKcjAC1BQDsZXZTQ3FByA1aH6Dv7hztDfKpCEMh/Tp645hFJNqc/dU76WqKEwlFPUt8EK9gkViOCo17KKLBzqOZw6/6TQ/yqordPAaKIhXYuIg6dd3ucK2z0MA6xQuwGrq2LlA+kAAuR1aNSRbBro5yXYuH3qrcjQgQzcAPV1vFqRWCBivstt3V9
  template:
    metadata:
      name: treelink-backup-s3
      namespace: treelink
